FROM cm2network/steamcmd:steam
RUN ./steamcmd.sh +force_install_dir /home/steam/rust-dedicated +login anonymous +app_update 258550 +quit
WORKDIR /home/steam/rust-dedicated

ENV OWNERID 76561198182710063
RUN echo "ownerid $OWNERID" >> ./server/your_server_identity/cfg/users.cfg

USER root
RUN apt update && apt install -y libsqlite3-dev

COPY ./startup.sh .
RUN chmod +x ./startup.sh
ENTRYPOINT ["./startup.sh"]
EXPOSE 28015 28016 28083
